<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Resources\v2rayN.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AssemblyTitle>VytswellRay</AssemblyTitle>
		<NeutralLanguage>ru-RU</NeutralLanguage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="WPF-UI" />
		<PackageReference Include="WPF-UI.Tray" />
		<PackageReference Include="ReactiveUI.WPF" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="app.manifest" />
		<Resource Include="Resources\v2rayN.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ServiceLib\ServiceLib.csproj" />
	</ItemGroup>

</Project>
