name: release Windows

on:
  workflow_dispatch:
  push:
    branches:
      - simplify-workplace-fork

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project: ./v2rayN/v2rayN.csproj
