name: build

on:
  workflow_call:
    inputs:
      project:
        required: false
        type: string
        default: './v2rayN/v2rayN.csproj'

jobs:
  build:
    name: build x64 arm64
    strategy:
      matrix:
        arch: [ x64, arm64 ]
    runs-on: windows-latest
    env:
      Output: "${{ github.workspace }}/${{ matrix.arch }}"
      RID: "win-${{ matrix.arch }}"
      Project: ${{ inputs.project }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup .NET
      uses: actions/setup-dotnet@v5.2.0
      with:
        dotnet-version: '8.0.x'

    - name: Build
      working-directory: ./v2rayN
      run: dotnet publish ${{ env.Project }} -c Release -r ${{ env.RID }} -p:SelfContained=true -p:EnableWindowsTargeting=true -o ${{ env.Output }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: ${{ matrix.arch }}
        path: ${{ matrix.arch }}
